services:
  dbai-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dbai
    volumes:
      - ./migrations/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
  dbai-redis:
    image: redis/redis-stack-server:latest
    container_name: dbai-redis
    ports:
      - 6379:6379
  dbai-redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: dbai-redis_insight
    ports:
      - 8001:8001


