services:
  dbai-pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dbai
    volumes:
      - ./migrations/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
  dbai-redis:
    image: redis/redis-stack-server:latest
    container_name: dbai-redis
    ports:
      - 6379:6379
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

